### ISSUE TITLE
Promises API

### ISSUE THREAD

**Issue by ted537** [jvdieten/diff-js-xml#14]
Would you be open to a promises version of the API? Or is there a reason that callbacks are preferred here?

**Comment by ted537** [comment]
Looking a little closer, could the diff simply return synchronously?

**Comment by ch3rn1k** [comment]
> Looking a little closer, could the diff simply return synchronously?

```ts
import { diffAsXml } from "diff-js-xml";

await new Promise((resolve) => {
  diffAsXml(lhsXML, rhsXML, schema, options, (result) => resolve(result));
});
```
