### ISSUE TITLE
Doesn't actually work in TypeScript projects

### ISSUE THREAD

**Issue by thaffenden** [jvdieten/diff-js-xml#7]
Not sure if I'm missing something, but you can't actually use this in a TypeScript project, as the import path for the models is incorrect.

When I install this into a project, then run the Typescript compiler (just using `./node_modules/.bin/tsc`), you get the following:

```
node_modules/diff-js-xml/dist/src/index.d.ts:1:25 - error 
TS2307: Cannot find module '../lib/model/field-options-schema' or its corresponding type declarations.1 import { ISchema } from "../lib/model/field-options-schema";

node_modules/diff-js-xml/dist/src/index.d.ts:2:31 - error 
TS2307: Cannot find module '../lib/model/options-model' or its corresponding type declarations.2 import { IOptionsModel } from "../lib/model/options-model";
```

An `outDir` is specified in `tsconfig.production.json`: https://github.com/jvdieten/diff-js-xml/blob/7d3a2f27fa914f41808514380a9da3ca9695ca91/tsconfig.production.json#L5

This means when it's installed into your project the type definitions sit at `dist/src`, not `src`:
![Screenshot from 2020-10-14 17-11-03](https://user-images.githubusercontent.com/14163530/96029520-b1eae300-0e52-11eb-83a2-1c158346fb9a.png)

Meaning the import paths in `index.d.ts` are incorrect.

If it was built without the `outDir` specified it should work as expected, but wanted to check if that's something you'd want to do before raising a PR to fix?

**Comment by jvdieten** [comment]
You are right good observation 👍 , would be great if you can create a PR for this have no time a the moment to do this myself. Thanks in advance!
